apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  ports:
    - port: 80
  selector:
    app: frontend
    tier: frontend
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: frontend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: frontend
        tier: frontend
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: frontend
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: wp-db-host
              key: hostname
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: frontend
        volumeMounts:
        - name: frontend-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: frontend-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim

